/**
 * W3C OWL 2 RL Conformance Tests
 *
 * Executes the approved OWL 2 RL test cases from the W3C test suite:
 *   https://www.w3.org/2009/11/owl-test/profile-RL.rdf
 *
 * Test fixtures were pre-generated by scripts/generate-w3c-fixtures.py, which
 * downloads the approved RL test cases and converts the embedded RDF/XML
 * ontologies to N-Triples format.
 *
 * Test types exercised:
 *  - PositiveEntailmentTest:  premise ⊢ conclusion (all conclusion triples must
 *                             appear in premise ∪ inferred)
 *  - NegativeEntailmentTest:  premise ⊬ non-conclusion (at least one triple in
 *                             non-conclusion must be absent from premise ∪ inferred)
 *  - ConsistencyTest:         no inconsistency triple is inferred
 *  - InconsistencyTest:       owl:Thing rdfs:subClassOf owl:Nothing is inferred
 */
import { describe, it, expect } from 'vitest';
import { RdfStore } from 'rdf-stores';
import DataFactory from '@rdfjs/data-model';
import type * as rdfjs from '@rdfjs/types';
import { NTriplesLexer, NTriplesParser, NTriplesReader } from '@faubulous/mentor-rdf-parsers';
import { OwlRlReasoner } from '../index.js';
import { owl, rdfs } from '../vocabulary.js';
import testCases from './w3c-conformance.json' with { type: 'json' };

interface TestCase {
    id: string;
    iri: string;
    types: string[];
    semantics: string[];
    description: string;
    premiseNTriples: string;
    conclusionNTriples: string;
    nonConclusionNTriples: string;
}

const { namedNode, quad } = DataFactory;

const reasoner = new OwlRlReasoner();
const lexer    = new NTriplesLexer();
const parser   = new NTriplesParser();
const reader   = new NTriplesReader();

/** Parse an N-Triples string into RDF/JS Quad objects. */
function parseNTriples(ntriples: string): rdfjs.Quad[] {
    const lexResult = lexer.tokenize(ntriples);
    parser.input = lexResult.tokens;
    const cst = parser.ntriplesDoc();
    return reader.readQuadContexts(cst) as unknown as rdfjs.Quad[];
}

/**
 * Stable canonical key for an RDF term.
 * Uses N-Triples-like encoding so NamedNodes, BlankNodes, and Literals are
 * all distinguishable and never collide with each other.
 */
function termKey(t: rdfjs.Term): string {
    switch (t.termType) {
        case 'NamedNode':  return `N\x00${t.value}`;
        case 'BlankNode':  return `B\x00${t.value}`;
        case 'Literal': {
            const lit = t as rdfjs.Literal;

            if (lit.language) return `L\x00${lit.value}\x00@${lit.language}`;
            return `L\x00${lit.value}\x00^${lit.datatype?.value ?? ''}`;
        }
        default: return `X\x00${t.value}`;
    }
}

function tripleKey(s: rdfjs.Term, p: rdfjs.Term, o: rdfjs.Term): string {
    return `${termKey(s)}\x01${termKey(p)}\x01${termKey(o)}`;
}

/** Load N-Triples into an RdfStore under the given named graph. */
function loadStore(ntriples: string, graphIri: string): ReturnType<typeof RdfStore.createDefault>['asDataset'] extends () => infer R ? R : never {
    const graph = namedNode(graphIri);
    const store = RdfStore.createDefault().asDataset();

    for (const triple of parseNTriples(ntriples)) {
        store.add(quad(triple.subject, triple.predicate, triple.object, graph));
    }
    return store as any;
}

interface CombinedGraph {
    /** Canonical triple keys for fast membership testing. */
    keys: Set<string>;
    /**
     * Index: (predicate-key + "\x01" + object-key) → subject term-keys.
     * Used to constrain blank-node candidates when the blank node appears
     * in subject position.
     */
    poToSubjects: Map<string, string[]>;
    /**
     * Index: (subject-key + "\x01" + predicate-key) → object term-keys.
     * Used to constrain blank-node candidates when the blank node appears
     * in object position.
     */
    spToObjects: Map<string, string[]>;
}

/** Build the combined graph from premise N-Triples and the reasoner's inferences. */
function buildCombined(premiseNTriples: string, graphIri: string): CombinedGraph {
    const store  = loadStore(premiseNTriples, graphIri);
    const g      = namedNode(graphIri);
    const premise  = parseNTriples(premiseNTriples);
    const axioms   = [...reasoner.getAxioms()];
    const inferred = [...reasoner.infer(store as any, g)];

    const keys       = new Set<string>();
    const poToSubjects = new Map<string, string[]>();
    const spToObjects  = new Map<string, string[]>();

    for (const q of [...premise, ...axioms, ...inferred]) {
        const sk = termKey(q.subject);
        const pk = termKey(q.predicate);
        const ok = termKey(q.object);
        keys.add(`${sk}\x01${pk}\x01${ok}`);

        const poKey = `${pk}\x01${ok}`;
        let subjects = poToSubjects.get(poKey);

        if (!subjects) { subjects = []; poToSubjects.set(poKey, subjects); }

        if (!subjects.includes(sk)) subjects.push(sk);

        const spKey = `${sk}\x01${pk}`;
        let objects = spToObjects.get(spKey);

        if (!objects) { objects = []; spToObjects.set(spKey, objects); }

        if (!objects.includes(ok)) objects.push(ok);
    }

    return { keys, poToSubjects, spToObjects };
}

/**
 * Check RDF simple entailment: does the combined graph entail the conclusion
 * document?  Blank nodes in the conclusion are treated as existentials and
 * matched against terms in the combined graph via constrained backtracking.
 *
 * For each blank node, candidates are found by looking up which terms appear
 * in the graph positions required by the first conclusion triple that mentions
 * the blank node, dramatically pruning the search space.
 */
function rdfEntails(graph: CombinedGraph, conclusionNTriples: string): boolean {
    const conclusion = parseNTriples(conclusionNTriples);

    if (conclusion.length === 0) return true;

    // Collect distinct blank-node values from the conclusion
    const bnodes: string[] = [];

    for (const q of conclusion) {
        if (q.subject.termType === 'BlankNode' && !bnodes.includes(q.subject.value)) bnodes.push(q.subject.value);

        if (q.object.termType  === 'BlankNode' && !bnodes.includes(q.object.value))  bnodes.push(q.object.value);
    }

    if (bnodes.length === 0) {
        return conclusion.every(q =>
            graph.keys.has(tripleKey(q.subject, q.predicate, q.object))
        );
    }

    return backtrack(conclusion, bnodes, 0, new Map<string, string>(), graph);
}

/**
 * Return candidate term-keys for a blank-node value given the conclusion triples
 * and the currently assigned mapping.  Picks the first conclusion triple that
 * mentions the blank node with all other terms already known (ground or mapped),
 * then does a single index lookup.  Falls back to an empty list if no
 * constraining triple can be found yet.
 */
function candidates(
    bnode: string,
    conclusion: rdfjs.Quad[],
    mapping: Map<string, string>,
    graph: CombinedGraph,
): string[] {
    for (const q of conclusion) {
        const sIsBnode = q.subject.termType === 'BlankNode' && q.subject.value === bnode;
        const oIsBnode = q.object.termType  === 'BlankNode' && q.object.value  === bnode;

        if (!sIsBnode && !oIsBnode) continue;

        const pk = termKey(q.predicate);

        if (sIsBnode) {
            // blank node is the subject — need (?, p, o).
            // Only constrain if we know the object already.
            if (q.object.termType === 'BlankNode') {
                const mapped = mapping.get(q.object.value);

                if (!mapped) continue; // object not yet bound
                return graph.poToSubjects.get(`${pk}\x01${mapped}`) ?? [];
            }
            const ok = termKey(q.object);
            return graph.poToSubjects.get(`${pk}\x01${ok}`) ?? [];
        } else {
            // blank node is the object — need (s, p, ?).
            if (q.subject.termType === 'BlankNode') {
                const mapped = mapping.get(q.subject.value);

                if (!mapped) continue; // subject not yet bound
                return graph.spToObjects.get(`${mapped}\x01${pk}`) ?? [];
            }
            const sk = termKey(q.subject);
            return graph.spToObjects.get(`${sk}\x01${pk}`) ?? [];
        }
    }
    return []; // no constraining triple found (shouldn't happen for well-formed conclusions)
}

function backtrack(
    conclusion: rdfjs.Quad[],
    bnodes: string[],
    idx: number,
    mapping: Map<string, string>,
    graph: CombinedGraph,
): boolean {
    if (idx === bnodes.length) {
        return conclusion.every(q => {
            const sk = q.subject.termType  === 'BlankNode' ? mapping.get(q.subject.value)! : termKey(q.subject);
            const pk = termKey(q.predicate);
            const ok = q.object.termType   === 'BlankNode' ? mapping.get(q.object.value)!  : termKey(q.object);
            return graph.keys.has(`${sk}\x01${pk}\x01${ok}`);
        });
    }

    const bnode = bnodes[idx];

    for (const candidate of candidates(bnode, conclusion, mapping, graph)) {
        mapping.set(bnode, candidate);

        if (backtrack(conclusion, bnodes, idx + 1, mapping, graph)) return true;
    }
    mapping.delete(bnode);
    return false;
}

const INCONSISTENCY_KEY = tripleKey(owl.Thing, rdfs.subClassOf, owl.Nothing);

/**
 * Tests that are outside the scope of the OWL 2 RL forward-chaining reasoner,
 * mapped to a human-readable reason for skipping.
 */
const SKIP_REASONS = new Map<string, string>([
    // Requires generating fresh blank nodes for owl:complementOf — not supported in forward-chaining RL
    ['DisjointClasses-001', 'requires blank-node creation (complementOf)'],
    ['DisjointClasses-003', 'requires blank-node creation (complementOf)'],
    // Requires generating a new owl:AllDifferent RDF list — not supported in forward-chaining RL
    ['New-Feature-DisjointObjectProperties-002', 'requires blank-node list creation (AllDifferent)'],
    ['New-Feature-DisjointDataProperties-002', 'requires blank-node list creation (AllDifferent)'],
    // Requires blank-node creation for an owl:complementOf class expression
    ['New-Feature-ObjectQCR-002', 'requires blank-node creation (complementOf)'],
    // Applies to OWL Full with comprehension principles, not OWL RL
    ['WebOnt-I5.26-010', 'requires OWL Full comprehension principles'],
    ['WebOnt-I5.5-005', 'requires OWL Full comprehension principles (ObjectUnionOf without axiom)'],
    // Applies to OWL 2 Direct Semantics only; not valid under OWL RL/RDF-Based Semantics
    ['WebOnt-I4.6-005-Direct', 'applies to OWL 2 Direct Semantics only'],
    ['WebOnt-equivalentClass-008-Direct', 'applies to OWL 2 Direct Semantics only'],
    // Requires resolving owl:imports, which is outside the reasoner scope
    ['WebOnt-imports-011', 'requires owl:imports resolution'],
    // Requires value-space intersection of numeric XSD datatypes (dt-not-type)
    ['WebOnt-I5.8-008', 'requires XSD value-space intersection (dt-not-type)'],
    ['WebOnt-I5.8-009', 'requires XSD value-space intersection (dt-not-type)'],
    // Complex OWL DL tests beyond OWL 2 RL scope (disjoint concept incoherence via tableau)
    ['WebOnt-description-logic-101', 'requires OWL DL tableau reasoning beyond RL scope'],
    ['WebOnt-description-logic-103', 'requires OWL DL tableau reasoning beyond RL scope'],
    ['WebOnt-description-logic-104', 'requires OWL DL tableau reasoning beyond RL scope'],
    // Empty fixture (fixture generation failed) and requires dt-not-type / dt-diff value-space reasoning
    ['functionality-clash', 'empty fixture; requires dt-not-type value-space reasoning'],
    ['string-integer-clash', 'empty fixture; requires dt-not-type value-space reasoning'],
    ['Plus and Minus Zero are Distinct', 'empty fixture; requires dt-diff float value-space reasoning'],
]);

const positiveTests      = (testCases as TestCase[]).filter(tc =>  tc.types.includes('PositiveEntailmentTest'));
const negativeTests      = (testCases as TestCase[]).filter(tc =>  tc.types.includes('NegativeEntailmentTest') && !tc.types.includes('PositiveEntailmentTest'));
const consistencyTests   = (testCases as TestCase[]).filter(tc =>  tc.types.includes('ConsistencyTest') && !tc.types.includes('PositiveEntailmentTest') && !tc.types.includes('NegativeEntailmentTest'));
const inconsistencyTests = (testCases as TestCase[]).filter(tc =>  tc.types.includes('InconsistencyTest'));

describe('W3C OWL 2 RL – PositiveEntailmentTest', () => {
    for (const tc of positiveTests) {
        const runner = SKIP_REASONS.has(tc.id) ? it.skip : it;

        runner(`${tc.id}: ${tc.description}`, () => {
            const graph = buildCombined(tc.premiseNTriples, tc.iri);

            expect(rdfEntails(graph, tc.conclusionNTriples)).toBe(true);
        });
    }
});

describe('W3C OWL 2 RL – NegativeEntailmentTest', () => {
    for (const tc of negativeTests) {
        const runner = SKIP_REASONS.has(tc.id) ? it.skip : it;

        runner(`${tc.id}: ${tc.description}`, () => {
            const graph = buildCombined(tc.premiseNTriples, tc.iri);

            expect(rdfEntails(graph, tc.nonConclusionNTriples)).toBe(false);
        });
    }
});

describe('W3C OWL 2 RL – ConsistencyTest', () => {
    for (const tc of consistencyTests) {
        const runner = SKIP_REASONS.has(tc.id) ? it.skip : it;

        runner(`${tc.id}: ${tc.description}`, () => {
            const graph = buildCombined(tc.premiseNTriples, tc.iri);

            expect(graph.keys.has(INCONSISTENCY_KEY)).toBe(false);
        });
    }
});

describe('W3C OWL 2 RL – InconsistencyTest', () => {
    for (const tc of inconsistencyTests) {
        const runner = SKIP_REASONS.has(tc.id) ? it.skip : it;

        runner(`${tc.id}: ${tc.description}`, () => {
            const graph = buildCombined(tc.premiseNTriples, tc.iri);

            expect(graph.keys.has(INCONSISTENCY_KEY)).toBe(true);
        });
    }
});
